# Generated by Django 5.0.1 on 2024-02-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0002_remove_faculty_faculty_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='faculty_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
