# Generated by Django 5.0.1 on 2024-02-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0003_faculty_faculty_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
