# Generated by Django 5.0.1 on 2024-02-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0006_attendancerecord_enrollmentnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='faculty_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='lecture_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='semester',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='time_slot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
