# Generated by Django 5.0.1 on 2024-02-29 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0009_student_is_active_student_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_staff',
        ),
    ]
