# Generated by Django 5.0.1 on 2024-03-01 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0011_student_is_active_student_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_staff',
        ),
    ]
