# Generated by Django 5.0.1 on 2024-03-01 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0016_student_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_staff',
        ),
    ]
